version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10

- package-ecosystem: 'github-actions'
  directory: '/'
  schedule:
    interval: 'monthly'
    
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
