name: 'Setup Julia environment'
description: 'Setup a Julia environment and add it to the PATH'
author: 'Sascha Mann'
inputs: 
  version:
    description: 'The Julia version to download (if necessary) and use. Example: 1.0.4'
    default: '1'
  arch:
    description: 'Architecture of the Julia binaries. Defaults to x64.'
    required: false
    default: 'x64'
runs:
  using: 'node12'
  main: 'lib/setup-julia.js'
branding:
  icon: 'download'
  color: 'green'
