name: Example builds (telemetry opt-out)

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['^1.5.0-0']
        julia-arch: [x64, x86]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        # 32-bit Julia binaries are not available on macOS
        exclude:
          - os: macOS-latest
            julia-arch: x86
    
    steps:
      - uses: actions/checkout@v1.0.0

      - name: "Install dependencies"
        run: |
          npm install
          npm run build
          npm run pack

      - name: "Set up Julia"
        uses: ./
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
          pkg-telemetry: 'false'

      - run: julia --version

      - run: cat "$HOME"/.julia/servers/telemetry.toml
        shell: bash

      - run: julia -e "using Pkg; Pkg.telemetryinfo()"
        shell: bash
